
name: Install Firefox MSI

on: 
  push:
    branches:
      - main

jobs:
  install-msi:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

   
    - name: Download Firefox MSI
      run: |
        Invoke-WebRequest -Uri "https://www.exemsi.com/downloads/packages/Firefox/Firefox%20Setup%2014.0.1.msi" -OutFile "$env:USERPROFILE\Downloads\FirefoxSetup.msi"
    - name: Install Firefox MSI
      run: |
        msiexec.exe /i "$env:USERPROFILE\Downloads\FirefoxSetup.msi" /quiet /norestart
