name: Install Firefox MSI

on: 
  push:
    branches:
      - main

jobs:
  install-msi:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set PowerShell Execution Policy
      run: |
        Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force

    - name: Define Output Path
      run: |
        $global:OutputPath = "$env:D:\msifile\FirefoxSetup.msi"
        Write-Output "Output Path: $global:OutputPath"

    - name: Download Firefox MSI
      run: |
        Invoke-WebRequest -Uri "https://www.exemsi.com/downloads/packages/Firefox/Firefox%20Setup%2014.0.1.msi" -OutFile $global:OutputPath

    - name: Install Firefox MSI
      run: |
        msiexec.exe /i $global:OutputPath /quiet /norestart

    
