name: Install Firefox MSI

on: 
  push:
    branches:
      - main

jobs:
  install-msi:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create Directory
      run: |
        powershell -Command "New-Item -Path 'D:\msifile' -ItemType Directory -Force"

    - name: Download Firefox MSI
      run: |
        powershell -Command "Invoke-WebRequest -Uri 'https://www.exemsi.com/downloads/packages/Firefox/Firefox%20Setup%2014.0.1.msi' -OutFile 'D:\msifile\FirefoxSetup.msi'"

    - name: Install Firefox MSI
      run: |
        powershell -Command "Start-Process msiexec.exe -ArgumentList '/i', 'D:\msifile\FirefoxSetup.msi', '/quiet', '/norestart' -NoNewWindow -Wait"

    - name: Verify Installation
      run: |
        powershell -Command "if (Test-Path 'C:\Program Files (x86)\Mozilla Firefox') { Write-Output 'Installation Successful!' } else { throw 'Installation failed!' }"
